minio:
  rootUser: "admin"
  rootPassword: "admin12345"
  mode: standalone  # Important: prevents 16 pods
  persistence:
    enabled: true
    existingClaim: ""
    storageClass: ""
    volumeName: ""
    accessMode: ReadWriteOnce
    size: 2Gi
  replicas: 1  # Use only in standalone mod
  resources:
    requests:
      memory: 1Gi
      cpu: 250m
    limits:
      memory: 2Gi
      cpu: 500m
