minio:
  rootUser: "admin"
  rootPassword: "admin12345"
  persistence:
    enabled: true
    existingClaim: ""
    storageClass: ""
    volumeName: ""
    accessMode: ReadWriteOnce
    size: 2Gi
  spec:
  	replicas: 2
  	template:
     spec:
       containers:
         resources:
           requests:
             memory: 1Gi
