minio:
  rootUser: "admin"
  rootPassword: "admin12345"
  persistence:
    enabled: true
    existingClaim: ""
    storageClass: ""
    volumeName: ""
    accessMode: ReadWriteOnce
    size: 2Gi
